name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all
      - name: Run clippy
        uses: auguwu/clippy-action@9817d076b82df0194935be9db6154c56ac07b317 # 1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-args: --all --all-features

  format:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Format Rust code
        run: cargo fmt --all -- --check

  coverage:
    permissions: {}
    runs-on: ubuntu-latest
    env:
      RUSTC_BOOTSTRAP: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          tool: cargo-llvm-cov
      - name: Run tests with coverage
        run: cargo llvm-cov test --all --all-features --codecov --output-path codecov-report.json
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          fail_ci_if_error: true
          files: codecov-report.json
          token: ${{ secrets.CODECOV_TOKEN }}
